version: '3.8'

services:
  php:
    image: php:8.2-cli   
    container_name: php_container
    volumes:
      - .:/var/www/html    
    working_dir: /var/www/html   
    tty: true           
    stdin_open: true
    networks:
      - exam-network
    command: bash -c "composer install && phpunit"
    ports:
      - "8081:8080"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

    entrypoint: |
      sh -c "
        apt-get update &&
        apt-get install -y git zip unzip libzip-dev pkg-config &&
        docker-php-ext-install zip &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer --version &&
        curl -sSL https://phar.phpunit.de/phpunit-9.phar -o /usr/local/bin/phpunit &&
        chmod +x /usr/local/bin/phpunit &&
        phpunit --version &&
        php -S 0.0.0.0:8080 -t /var/www/html/app/public  
      "

networks:
  exam-network:
    driver: bridge
